[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"

[[services]]
name = "backend"
source = "./backend"
startCommand = "npm run start"

[services.variables]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "frontend"
source = "./frontend"
buildCommand = "npm run build"
startCommand = "npx serve -s dist -l 8080"

[services.variables]
PORT = "8080"